#!/usr/bin/env python

# Copyright 2013, Sebastian Jeltsch (sjeltsch@kip.uni-heidelberg.de)
# Distributed under the terms of the LGPLv3 or newer.

import sys, os

components = ['gtest', '..']
recurse    = lambda ctx : map(lambda proj: ctx.recurse(proj), components)

def options(opt):
    recurse(opt)
    opt.load('g++')

def configure(cfg):
    recurse(cfg)
    cfg.load('g++')

    cfg.check_cxx(lib='mongoclient', uselib_store='MONGO')

def build(bld):
    recurse(bld)

    bld(
        target          = 'main',
        features        = 'cxx cxxprogram',
        source          = bld.path.ant_glob('*.cc') + \
                bld.path.ant_glob('regress/*.cc'),
        use             = ['gtest', 'boost_mongo', 'MONGO' ],
        install_path    = 'bin',
        cxxflags        = [
                '-g',
                '-O0',
                '-Wall',
                '-Wextra',
                '-pedantic',
                '-Wno-long-long',
                '-Wno-variadic-macros',
            ],
        includes       = '.',
    )
