#!/usr/bin/env python
import sys, os

components = ['gtest', '..']
recurse    = lambda ctx : map(lambda proj: ctx.recurse(proj), components)

def options(opt):
    recurse(opt)
    opt.load('g++')

def configure(cfg):
    recurse(cfg)
    cfg.load('g++')

def build(bld):
    recurse(bld)

    bld(
        target          = 'main',
        features        = 'cxx cxxprogram',
        source          = bld.path.ant_glob('*.cc'),
        use             = ['gtest', 'boost_mongo' ],
        install_path    = 'bin',
        cxxflags        = [
                '-g',
                '-O0',
                '-Wall',
                '-Wextra',
                '-pedantic',
                '-Wno-long-long',
                '-Wno-variadic-macros',
            ],
        includes       = '.',
    )
