#!/usr/bin/env python

# Copyright 2013, Sebastian Jeltsch (sjeltsch@kip.uni-heidelberg.de)
# Use, modification and distribution is subject to the Boost Software
# License, Version 1.0. (See accompanying file LICENSE_1_0.txt or copy at
# http://www.boost.org/LICENSE_1_0.txt)

import sys, os

components = ['../..']
recurse    = lambda ctx : map(lambda proj: ctx.recurse(proj), components)

def options(opt):
    recurse(opt)
    opt.load('g++')
    opt.load('boost')

def configure(cfg):
    recurse(cfg)
    cfg.load('g++')
    cfg.load('boost')

    cfg.check_boost(
            lib='serialization system thread filesystem',
            uselib_store='BOOST_COMMON')

    cfg.check_boost(
            lib='unit_test_framework',
            uselib_store='BOOST_TEST')

    cfg.check_cxx(lib='mongoclient', uselib_store='MONGO')
    cfg.check_cxx(lib='pthread')
    cfg.check_cxx(lib='dl')

def build(bld):
    recurse(bld)

    cxxflags = [ '-g', '-O0', ]

    bld.shlib(
        target = 'boost_test_common',
        source  = [
            'A.cpp',
            'polymorphic_base.cpp',
            'polymorphic_derived2.cpp',
            'polymorphic_derived1.cpp',
            'test_polymorphic_A.cpp',
            'test_polymorphic2imp.cpp',
            ],
        use = [ 'BOOST_COMMON', 'boost_mongo_inc' ],
        cxxflags = cxxflags,
        includes = '.',
        install_path = 'lib')

    tests = [
            'test_array.cpp',
            'test_binary.cpp',
            'test_bitset.cpp',
            'test_class_info_save.cpp',
            'test_complex.cpp',
            'test_contained_class.cpp',
            'test_delete_pointer.cpp',
            'test_deque.cpp',
            'test_derived.cpp',
            'test_derived_class_ptr.cpp',
            'test_diamond.cpp',
            'test_diamond_complex.cpp',
            'test_list.cpp',
            'test_list_ptrs.cpp',
            'test_map.cpp',
            'test_mi.cpp',
            'test_multiple_inheritance.cpp',
            'test_multiple_ptrs.cpp',
            'test_new_operator.cpp',
            'test_no_rtti.cpp',
            'test_non_intrusive.cpp',
            'test_null_ptr.cpp',
            'test_nvp.cpp',
            'test_object.cpp',
            'test_optional.cpp',
            'test_pimpl.cpp',
            'test_primitive.cpp',
            'test_private_base.cpp',
            'test_recursion.cpp',
            'test_registered.cpp',
            'test_shared_ptr.cpp',
            'test_shared_ptr_132.cpp',
            'test_shared_ptr_multi_base.cpp',
            'test_simple_class.cpp',
            'test_simple_class_ptr.cpp',
            'test_split.cpp',
            'test_tracking.cpp',
            'test_variant.cpp',
            'test_vector.cpp',
            'test_polymorphic.cpp',
            'test_polymorphic2.cpp',

            # The following tests are excluded. A meaningful
            # explanation should be provided alongside.

            #'test_dll_exported.cpp'     # overwrites BOOST_ARCHIVE_TEST macro
                                         # to always use text_archive only
                                         #   -> not interesting.

            #'test_not_serializable.cpp' # according to header, compilation is
                                         # supposed to fail.
        ]

    for test in tests:
        name = os.path.splitext(test)[0]

        bld.program(
            target          = name,
            source  = [ test ],
            use = [
                'boost_test_common',
                'boost_mongo',
                'BOOST_TEST',
                'MONGO',
                'PTHREAD'
                ],
            cxxflags = cxxflags,
            includes = '.',
            install_path = 'bin')


    # Dynamic Library Plugin Test
    bld.shlib(
        target = 'plugin_polymorphic_derived2',
        source  = [
            'polymorphic_base.cpp',
            'polymorphic_derived2.cpp',

            #'polymorphic_derived1.cpp',
            #'dll_derived2.cpp',
            #'dll_base.cpp',
            ],
        use = [ 'BOOST_COMMON', 'DL', 'boost_mongo_inc' ],
        cxxflags = cxxflags + [ '-fPIC' ],
        linkflags = [ '-zdefs' ],
        includes = '.',
        install_path = 'lib')

    bld.program(
        target          = 'test_dll_plugin',
        source  = [ 'test_dll_plugin.cpp', ],
        use = [
            'plugin_polymorphic_derived2',
            'boost_mongo',
            'BOOST_TEST',
            'MONGO',
            'PTHREAD',
            ],
        cxxflags = cxxflags,
        includes = '.',
        install_path = 'bin')
